
project_id = "chmwoegkgcsjsibfqmby"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:5173"

[storage]
enabled = true

[edge_functions]
enabled = true

[[edge_functions.routes]]
path = "/get_brand_settings"
function = "get_brand_settings"

[[edge_functions.routes]]
path = "/upsert_brand_settings"
function = "upsert_brand_settings"
